---
abstract: 'JBD is a namespace'
author:
  - 'Joel Dalley <joeldalley@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.014, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: JBD
requires:
  Carp: 0
  DBI: 0
  Data::Dumper: 0
  Exporter: 0
  File::Slurp: 0
  Module::Load: 0
  Scalar::Util: 0
  Storable: 0
  Time::Local: 0
  constant: 0
  overload: 0
  strict: 0
  warnings: 0
version: 0.04
